### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Bluscream** [SpEcHiDe/NoWhatOpen#1]
Doesnt open anything

**Comment by Bluscream** [comment]
Android 5.1 sr+tock on sm-t555

**Comment by SpEcHiDe** [comment]
You might not have understood, what this application does! 
This fact was clearly mentioned in the store listing description.
Th
```quote
this application is useless to you!
https://blog.shrimadhavuk.me/v1.0-promotion/
```

**Comment by Bluscream** [comment]
@SpEcHiDe The blog entry is 404 sow how should we be supposed to know anything about it? And yes i've read and understood the sourcecode.

**Comment by Bluscream** [comment]
I just think wa is no longer registered as smsto: handler.

**Comment by SpEcHiDe** [comment]
@Bluscream The application is working on my device!

**Comment by Bluscream** [comment]
Maybe its because of WA+ or GBWhatsapp

**Comment by SpEcHiDe** [comment]
WhatsApp has an handler called smsto: in it's current beta version! 
I have not used WhatsApp+, so I do not know about it!
